package edu.ntnu.stud.enums;

public enum Event {
  DARK_MODE_TOGGLED, HOME, NEW_GAME, CONTINUE_GAME, LOAD_PREVIOUS_GAME, HELP, CLEAR_CANVAS, SAVE_GAME, RUN, BARNSLEY, JULIA, SIERPINSKI, STEPS, CONSTANT, MATRIX00, MATRIX01, MATRIX10, MATRIX11;
}
