package edu.ntnu.stud.enums;

public enum Event {
  DARK_MODE_TOGGLED, CHAOS_GAME_DESCRIPTION_UPDATED, CANVAS_SIZE_UPDATED, SET_PRESET, RUN_CHAOS_GAME, STEPS_RAN, LOAD_FILE, SAVE_FILE, OPEN_EDIT_DESCRIPTION_DIALOG, UPDATE_DESCRIPTION;
}
